### ISSUE TITLE
ESX GetPlayerData

### ISSUE THREAD

**Issue by bobSmith121** [ENT510/LGF-Report-System#1]
Using esx, when trying to  do /report 
Client error: 
![image](https://github.com/ENT510/LGF-Report-System/assets/172206120/d8d3375d-30b8-41a6-988d-2b9a9e173750)

if you do /reportmenu 
Server error:
![image](https://github.com/ENT510/LGF-Report-System/assets/172206120/d1b5d7bc-89a5-4d4b-9e4d-f612fd105058)

**Comment by ENT510** [comment]
ok try now

**Comment by bobSmith121** [comment]
Works

**Comment by ENT510** [comment]
good
